# Generated by Django 2.0.1 on 2018-09-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20180906_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='signer_mobile',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
    ]
